apiVersion: v1
kind: Service
metadata:
  name: user-management-db-svc
  namespace: user-management-namespace
spec:
  selector:
    app: user-management-mysql 
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None

