apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-backend-deployment
  labels:
    app: user-management-backend-label
  namespace: user-management-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-management-backend-pod
  template:
    metadata:
      labels:
        app: user-management-backend-pod
    spec:
      containers:
        - name: user-management-backend-con
          image: pankajarya12345/user-management-app-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"

            - name: DB_HOST
              value: "user-management-db-svc.user-management-namespace.svc.cluster.local"

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: database
          

