apiVersion: v1
kind: Service
metadata:
  name: user-management-backend-svc
  labels:
    app: user-management-backend-svc
  namespace: user-management-namespace
spec:
  selector:
    app: user-management-backend-pod
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
