apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-frontend-deployment
  labels:
    app: user-management-frontend-label
  namespace: user-management-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-management-frontend-pod
  template:
    metadata:
      labels:
        app: user-management-frontend-pod
    spec:
      containers:
        - name: user-management-frontend-con
          image: pankajarya12345/user-management-app-frontend:latest
          ports:
            - containerPort: 80
