apiVersion: v1
kind: Service
metadata:
  name: user-management-frontend-svc
  labels:
    app: user-management-frontend-svc
  namespace: user-management-namespace
spec:
  selector:
    app: user-management-frontend-pod
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080  # Choose an available port in the NodePort range (30000-32767)
